version: '3.8'

services:
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8084:8084"
    depends_on:
      - keycloak
      - auth-service
      - hotel-service
      - calculation-service
      - evidence-service

  hotel-service:
    build:
      context: ./hotel-service
    ports:
      - "8081:8080"

  calculation-service:
    build:
      context: ./calculation-service
    ports:
      - "8082:8080"

  evidence-service:
    build:
      context: ./evidence-service
    ports:
      - "8083:8080"

  auth-service:
    build:
      context: ./auth-service
    ports:
      - "8085:8085"

  keycloak:
    image: quay.io/keycloak/keycloak:20.0.5
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5431
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      KC_HOSTNAME_STRICT: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    #volumes:
    #  - ./init-keycloak.sh:/opt/keycloak/init-keycloak.sh
    command:
      - start-dev
      - --http-enabled=true
      - --hostname-strict=false
      - --hostname-strict-https=false
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    #command: ["/bin/sh", "-c", "start-dev && /opt/keycloak/init-keycloak.sh"]
    #entrypoint:
    #command:
      #- /bin/bash
      #- -c
      #- |
      #  /opt/keycloak/init-keycloak.sh &
      #  /opt/keycloak/bin/kc.sh start-dev --http-enabled=true --hostname-strict=false --hostname-strict-https=false

      #- |
      #  /opt/keycloak/bin/kc.sh start-dev --http-enabled=true --hostname-strict=false --hostname-strict-https=false &
      #  sleep 20 &&
      #  bash /opt/keycloak/init-keycloak.sh
    #restart: unless-stopped
    #networks:
    #  - keycloak-network

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: keycloak
    ports:
      - "5431:5431"
    expose:
      - "5431"
    command: -p 5431
    #networks:
    #  - keycloak-network

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

networks:
  keycloak-network:
    driver: bridge
